(() => {
const U='https://ufoulgbiqgjriwapuopc.supabase.co',K='sb_publishable_BRqfs9ElsX5mPJgrIxdFrQ_884V2SwA',db=supabase.createClient(U,K);
let clientId='',rows=[],source='all';
const $=x=>document.getElementById(x);
async function boot(){const {data:{session}}=await db.auth.getSession();if(!session){location.href='login.html';return}const {data:c,error}=await db.from('client_data').select('client_id,business_name,name,full_name').eq('auth_user_id',session.user.id).maybeSingle();if(error||!c?.client_id)throw new Error(error?.message||'Client account not found');clientId=c.client_id;$('businessName').textContent=c.business_name||c.name||c.full_name||'Business';$('clientId').textContent=clientId;await load();$('boot').remove()}
async function load(){let q=db.from('orders').select('id,customer_id,quantity,price_at_order,total_amount,product_title,color_at_order,size_at_order,fabric_at_order,status,payment_status,source,source_channel,source_reference,lead_id,created_at').eq('client_id',clientId).order('created_at',{ascending:false}).limit(300);if(source!=='all')q=q.eq('source_channel',source);const {data,error}=await q;if(error)throw error;rows=data||[];renderStats();render()}

function renderStats(){const all=source==='all'?rows:rows;const count=x=>all.filter(o=>String(o.source_channel||o.source||'other').toLowerCase()===x).length;$('total').textContent=all.length;$('whatsapp').textContent=count('whatsapp');$('instagram').textContent=count('instagram');$('website').textContent=count('website');$('paid').textContent=all.filter(o=>String(o.payment_status).toLowerCase()==='paid').length}
function render(){const s=$('search').value.toLowerCase().trim(),st=$('status').value;const out=rows.filter(o=>(!s||`${o.product_title||''} ${o.id} ${o.customer_id}`.toLowerCase().includes(s))&&(st==='all'||o.status===st));$('orderList').innerHTML=out.map(o=>{const ch=String(o.source_channel||o.source||'other').toLowerCase();const icon=ch==='whatsapp'?'🟢':ch==='instagram'?'🟣':ch==='website'?'🔵':'⚪';return `<div class="order-row"><div class="customer"><b>${esc(o.product_title||'Order')}</b><small>#${esc(o.id.slice(0,8))} · ${o.quantity||1} item(s)</small></div><div class="product">${esc([o.color_at_order,o.size_at_order,o.fabric_at_order].filter(Boolean).join(' · ')||'—')}</div><div class="money">₹${Number(o.total_amount||o.price_at_order||0).toLocaleString('en-IN')}</div><div><span class="source ${esc(ch)}">${icon} ${esc(ch)}</span></div><div class="status">${esc(o.status||'new')} · ${esc(o.payment_status||'')}</div><button class="lead-btn" data-id="${o.id}" data-lead="${o.lead_id||''}">${o.lead_id?'✓ Lead':'＋ Add to Leads'}</button></div>`}).join('')||'<div class="empty">No orders match this view.</div>';document.querySelectorAll('.lead-btn').forEach(b=>b.onclick=()=>addLead(b.dataset.id))}
async function addLead(orderId){const o=rows.find(x=>x.id===orderId);if(!o)return;if(o.lead_id)return;const {data:customer}=await db.from('customers').select('id,name,mobile').eq('id',o.customer_id).eq('client_id',clientId).maybeSingle();if(!customer)return alert('Customer profile not found');let {data:lead}=await db.from('leads').select('id').eq('client_id',clientId).eq('customer_id',customer.id).maybeSingle();if(!lead){const r=await db.from('leads').insert({client_id:clientId,customer_id:customer.id,name:customer.name,mobile:customer.mobile,whatsapp:customer.mobile,source:String(o.source_channel||o.source||'other'),source_ref:o.id,product_service:o.product_title,status:'new',priority:'normal'}).select('id').single();if(r.error)return alert(r.error.message);lead=r.data}const r=await db.from('orders').update({lead_id:lead.id}).eq('id',orderId).eq('client_id',clientId);if(r.error)return alert(r.error.message);await load()}

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');source=b.dataset.source;load()});$('search').oninput=render;$('status').onchange=render;$('logout').onclick=async()=>{await db.auth.signOut();location.href='login.html'};boot().catch(e=>{$('boot').innerHTML=`<span style="color:#ff6472">${esc(e.message)}</span>`});
})();
